name: PR Merge Email Notification
 
on:
  pull_request:
    types: [closed]
 
jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
 
    steps:
      - name: Get PR author email
        id: email
        run: |
          echo "EMAIL=${{ github.event.pull_request.user.login }}@users.noreply.github.com" >> $GITHUB_OUTPUT
 
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
 
          subject: "Your Terraform PR was merged"
          to: ${{ steps.email.outputs.EMAIL }}
          from: GitHub Notification <${{ secrets.EMAIL_USERNAME }}>
 
          body: |
            Hello,
 
            Your pull request has been merged successfully.
 
            Repository: ${{ github.repository }}
            PR Number: #${{ github.event.pull_request.number }}
            Commit ID: ${{ github.event.pull_request.merge_commit_sha }}
 
            Status: MERGED
 
            Regards,
            Platform Team
